version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    hostname: '{{.Node.Hostname}}-kibana'
    ports:
      - '5601:5601'

    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - 'elasticsearch'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    hostname: '{{.Node.Hostname}}-elasticsearch'
    ports:
      - '9200:9200'
      - '9300:9300'

networks:
  default:
    driver: bridge
